# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "9.3.1"

  on_macos do
    on_arm do
      sha256 "3599530ae0e501b5ec423631b06c24a6c58a916b95808df1fe35332f3302993f"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee7b3bd0b3ef382bef916ddd330bf766dac2bfb4524e645422d25a7534bea484"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3feac88f85f4952e2214931429abb3d4d205db1d0d0eb3d8291547fd40c2252f"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8631c724274a1e65b8e336f7805b16f800a336cb2c97010b0b67b99d0434d1e7"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warden"
  desc "Spawn, monitor, and tear down a fleet of coding agents (worktree isolation, cost tracking, TUI/web cockpit)"
  homepage "https://srjn45.github.io/warden/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    warden drives coding-agent CLIs you install separately — e.g. Claude Code:
      https://docs.claude.com/claude-code
    Start here:
      warden setup      # check/install runtime deps
      warden tutorial   # guided tour
    The repo's install script also creates a `wd` alias; with the cask, add
    your own: alias wd=warden
  EOS
end
