# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "9.6.0"

  on_macos do
    on_arm do
      sha256 "61fc397b2d07560db42ac673df53411d286a7f27d7ee2c87d86556a792bc8e4b"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee4630289bb51b9f698ed1808cd4f084b6e3f1fd3a71fe306b3de93039ffa6db"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "50ff7c489340f37ea2c1d0f273ec3d8f8400068fb0e3421964b1755733ff18b7"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5749ad13cf31af256563b5db2d9ab010fd703d296cb4e86a150c898f59ed4d8"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warden"
  desc "Spawn, monitor, and tear down a fleet of coding agents (worktree isolation, cost tracking, TUI/web cockpit)"
  homepage "https://srjn45.github.io/warden/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    warden drives coding-agent CLIs you install separately — e.g. Claude Code:
      https://docs.claude.com/claude-code
    Start here:
      warden setup      # check/install runtime deps
      warden tutorial   # guided tour
    The repo's install script also creates a `wd` alias; with the cask, add
    your own: alias wd=warden
  EOS
end
