# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "9.7.0"

  on_macos do
    on_arm do
      sha256 "1727fb772f190823af3e435ae2873ae12320137b2be9ca21e4bafd5d156794e4"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "284ba6ee7df08f68a8f5e8ab59335eaf16131e1d273c94fb43bfd593cf182626"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a7dc66b4ce2be99d7fb9af2d513771571a69bdea8e86b34e262f7beb26e5d78"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "18edbe150a940e8f58d0d24fc307a510fbc297fa6f5e3366521aac4486c05f04"
      url "https://github.com/srjn45/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
  end

  name "warden"
  desc "Spawn, monitor, and tear down a fleet of coding agents (worktree isolation, cost tracking, TUI/web cockpit)"
  homepage "https://srjn45.github.io/warden/"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    warden drives coding-agent CLIs you install separately — e.g. Claude Code:
      https://docs.claude.com/claude-code
    Start here:
      warden setup      # check/install runtime deps
      warden tutorial   # guided tour
    The repo's install script also creates a `wd` alias; with the cask, add
    your own: alias wd=warden
  EOS
end
